image: docker.mamdev.server.lan/internal/mamido/ci-runner:latest

# automatically move artifacts,
# resolve MAMDEVQA-Ticket
variables:
  CREATE_MAMDEVQA_DUMP_JSON: "true"

Verify Branches:
  script:
    - npm install
    - npm test
    - npm run build
    - mvn-branch-sonar-comments
  except:
    - master@iscomp/sonar-gitlab-plugin
    - tags@iscomp/sonar-gitlab-plugin

Deploy Master and Tags:
  script:
    - npm install
    - npm test
    - npm run build
    - mvn-master
  only:
    - master@iscomp/sonar-gitlab-plugin
    - tags@iscomp/sonar-gitlab-plugin

prepare release:
  stage: deploy
  only:
    - master
  when: manual
  script:
    - mvn-update-parent
    - mvn -V -B -DpushChanges=false -Dmessage='Update PortalPom' scm:checkin
    - npm install
    - npm test
    - npm run build
    - mvn-prepare-release -DcheckModificationExcludeList=pom.xml,package-lock.json

deploy release:
  stage: deploy
  only:
    - tags
  script:
    - npm install
    - npm test
    - npm run build
    - mvn-stage-release

# Job for testing the SQ 7.9 installation
Test SonarQube7.9 QA:
  image: docker.mamdev.server.lan/internal/mamido/ci-runner-base-adoptopenjdk11:stretch
  stage: test
  script:
    - mvn -B -V verify sonar:sonar
      -Ddependency-check.skip
      -Dsonar.host.url=https://mam-sonar-qa-bs01.mamdev.server.lan -Dsonar.analysis.mode=publish
  only:
    - master
  allow_failure: true
